#### why we need numpy - basic list it cannot work as a matrix and doing math will be time taking
```
x = [1,2,3]
y = [3,4,5]
x * y
```
### so we use numpy instead of simple list


in the terminal or cmd
```
pip install numpy
```

In [33]:
import numpy as np

In [34]:
x = np.array([1,2,3])
type(x)

numpy.ndarray

In [35]:
x

array([1, 2, 3])

In [36]:
print(x)

[1 2 3]


In [37]:
x.dtype

dtype('int32')

In [38]:
x.shape

(3,)

In [39]:
x.ndim

1

In [40]:
x2 = np.array([[2,3],[5,3]])
print(x2)

[[2 3]
 [5 3]]


In [41]:
x3 = np.array([[[1,2],[2,3]],[[3,4],[4,5]]])
print(x3)

[[[1 2]
  [2 3]]

 [[3 4]
  [4 5]]]


In [42]:
x = [1,2,3]
y = [3,4,5]
z = [2,4,5]
z3 = np.array([x,y,z])
print(z3)

[[1 2 3]
 [3 4 5]
 [2 4 5]]


In [43]:
np.array([x,x,x])

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

# math in matrix

In [44]:
x = np.array([x,y,z])

In [45]:
y = np.array([y,z,y])

In [46]:
print(x)

[[1 2 3]
 [3 4 5]
 [2 4 5]]


In [47]:
print(y)

[[3 4 5]
 [2 4 5]
 [3 4 5]]


In [48]:
x + y # addition

array([[ 4,  6,  8],
       [ 5,  8, 10],
       [ 5,  8, 10]])

In [49]:
x * y # multiplication element wise

array([[ 3,  8, 15],
       [ 6, 16, 25],
       [ 6, 16, 25]])

In [50]:
x / y

array([[0.33333333, 0.5       , 0.6       ],
       [1.5       , 1.        , 1.        ],
       [0.66666667, 1.        , 1.        ]])

In [51]:
x - y

array([[-2, -2, -2],
       [ 1,  0,  0],
       [-1,  0,  0]])

In [52]:
x // y

array([[0, 0, 0],
       [1, 1, 1],
       [0, 1, 1]], dtype=int32)

In [53]:
x > y

array([[False, False, False],
       [ True, False, False],
       [False, False, False]])

In [54]:
x == y

array([[False, False, False],
       [False,  True,  True],
       [False,  True,  True]])

In [55]:
a = np.array([[1,2],[2,1]])
b = np.array([[2,1],[3,2]])

In [56]:
print(a)
print(b)

[[1 2]
 [2 1]]
[[2 1]
 [3 2]]


In [57]:
a * b

array([[2, 2],
       [6, 2]])

In [58]:
np.dot(a,b)

array([[8, 5],
       [7, 4]])

In [59]:
np.inner(a,b)

array([[4, 7],
       [5, 8]])

In [60]:
np.kron(a,b)

array([[2, 1, 4, 2],
       [3, 2, 6, 4],
       [4, 2, 2, 1],
       [6, 4, 3, 2]])

# indexing,slicing in numpy

In [61]:
print(x)

[[1 2 3]
 [3 4 5]
 [2 4 5]]


In [62]:
x[0,0]

1

In [63]:
x[0,2]

3

In [64]:
x[3,3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [55]:
print(np.random.randint(1,100,(6,6)))

[[20 25 44 36 74 75]
 [71 73 41 80 30 93]
 [97 69 93 38 77 60]
 [49 75  2 56 19 57]
 [ 9 25  2 68 24 37]
 [35 16 60 35  3 60]]


# numpy basic functions

In [4]:
x = np.random.randint(1,10,28)

In [5]:
x

array([7, 8, 2, 8, 8, 8, 6, 8, 8, 2, 1, 1, 6, 6, 3, 8, 2, 4, 8, 3, 3, 4,
       4, 8, 1, 5, 2, 2])

In [6]:
x.reshape((7,4))

array([[7, 8, 2, 8],
       [8, 8, 6, 8],
       [8, 2, 1, 1],
       [6, 6, 3, 8],
       [2, 4, 8, 3],
       [3, 4, 4, 8],
       [1, 5, 2, 2]])

In [8]:
x = x.reshape((2,7,2))
print(x)

[[[7 8]
  [2 8]
  [8 8]
  [6 8]
  [8 2]
  [1 1]
  [6 6]]

 [[3 8]
  [2 4]
  [8 3]
  [3 4]
  [4 8]
  [1 5]
  [2 2]]]


In [17]:
xa = x.reshape((4,7))
xa

array([[7, 8, 2, 8, 8, 8, 6],
       [8, 8, 2, 1, 1, 6, 6],
       [3, 8, 2, 4, 8, 3, 3],
       [4, 4, 8, 1, 5, 2, 2]])

In [18]:
xa.shape

(4, 7)

In [19]:
# transpose rows to cols, cols to rows
xa.transpose()

array([[7, 8, 3, 4],
       [8, 8, 8, 4],
       [2, 2, 2, 8],
       [8, 1, 4, 1],
       [8, 1, 8, 5],
       [8, 6, 3, 2],
       [6, 6, 3, 2]])

In [22]:
xa.T # transpose

array([[7, 8, 3, 4],
       [8, 8, 8, 4],
       [2, 2, 2, 8],
       [8, 1, 4, 1],
       [8, 1, 8, 5],
       [8, 6, 3, 2],
       [6, 6, 3, 2]])

In [26]:
xa.sum() 

136

In [29]:
xa

array([[7, 8, 2, 8, 8, 8, 6],
       [8, 8, 2, 1, 1, 6, 6],
       [3, 8, 2, 4, 8, 3, 3],
       [4, 4, 8, 1, 5, 2, 2]])

In [28]:
xa.sum(axis=1) # row sum

array([47, 32, 31, 26])

In [31]:
xa.sum(axis=0) # col sum

array([22, 28, 14, 14, 22, 19, 17])

In [34]:
xa.mean()

4.857142857142857

In [35]:
xa.std()

2.6418917155581325

In [36]:
xa.min()

1

In [37]:
xa.max()

8

In [41]:
xa.sort(axis=0)
xa

array([[1, 1, 2, 3, 4, 5, 8],
       [1, 2, 2, 4, 4, 8, 8],
       [2, 3, 3, 6, 6, 8, 8],
       [2, 6, 7, 8, 8, 8, 8]])

In [42]:
xa.sort(axis=1)
xa

array([[1, 1, 2, 3, 4, 5, 8],
       [1, 2, 2, 4, 4, 8, 8],
       [2, 3, 3, 6, 6, 8, 8],
       [2, 6, 7, 8, 8, 8, 8]])

In [48]:
xa

array([[1, 1, 2, 3, 4, 5, 8],
       [1, 2, 2, 4, 4, 8, 8],
       [2, 3, 3, 6, 6, 8, 8],
       [2, 6, 7, 8, 8, 8, 8]])

In [50]:
# boolean filter
xa > 3

array([[False, False, False, False,  True,  True,  True],
       [False, False, False,  True,  True,  True,  True],
       [False, False, False,  True,  True,  True,  True],
       [False,  True,  True,  True,  True,  True,  True]])

In [53]:
xa[xa > 3] # using a boolean filter

array([4, 5, 8, 4, 4, 8, 8, 6, 6, 8, 8, 6, 7, 8, 8, 8, 8])

In [54]:
filter8 = xa == 8
xa[filter8]

array([8, 8, 8, 8, 8, 8, 8, 8, 8])

In [57]:
xa[(xa >=4) & (xa <7)]

array([4, 5, 4, 4, 6, 6, 6])

In [60]:
z = np.random.randint(1,100,(3,5))

In [62]:
print(z)

[[43 17 37 15 74]
 [16 37 55 99 68]
 [40  5 10 73 37]]


In [65]:
z.argmin(axis=1)

array([3, 0, 1], dtype=int64)

In [ ]:
z.a